Lab3
bushkovsky/is-web-y26 pull request #2
Opened 2024-11-14 10:35 UTC by bushkovsky

2024-11-28 11:21 UTC, BakasaRus requested changes
Чем отличается `flex` от `grid`?

2024-11-28 11:21 UTC, BakasaRus commented on site.html
> +        <div class="table">
Хочется именно тег `table` и прочие подобные, тут немного переделывать, на самом деле

2024-11-28 11:21 UTC, BakasaRus commented on site.html
> +        <div class="table">
Ещё вопрос: как получилось ровно 5 столбцов, если это явно нигде не указано?

2024-12-04 21:49 UTC, bushkovsky commented on site.html
> +        <div class="table">
Flexbox – это общепринятое сокращение для Flexible Box Module (модуль гибкого контейнера), который представляет собой одномерную модель макета. Это значит, что одновременно он может работать только со строкой или столбцом, но не с обоими сразу. Flexbox эффективно справляется с выравниванием, распределением и направлением элементов страницы.

Двумя основными понятиями этой модели макета являются главная ось и поперечная ось. Главная ось flex-контейнера – это основное направление, вдоль которого выстраиваются flex-элементы, поперечная же ось ей перпендикулярна.  

CSS grid (сетка) представляет собой мощный двухмерный макет, при использовании которого можно одновременно работать со строками и столбцами. В основе CSS Grid лежит неявное разделение экрана на сетку из 12 частей, в которые в итоге и вписываются элементы.

Преимущество этой технологии перед Flexbox и другими видами макетов в ее возможности работать двухмерно. При этом она также упрощает позиционирование, и элементы контейнера могут размещаться, перекрывая друг на друга.  

так лучше гриды юзать для каркаса сайта, а флоксы для контента

2024-12-11 19:24 UTC, merged