Lab4
bushkovsky/is-web-y26 pull request #3
Opened 2024-11-14 13:45 UTC by bushkovsky

2024-11-28 11:30 UTC, BakasaRus requested changes

2024-11-28 11:30 UTC, BakasaRus commented on js/script.js
> +    };
Эта функция выводит на секунду меньше того, что есть на самом деле

Проверить можно в девтулзах во вкладке "Network"

2024-11-28 11:30 UTC, BakasaRus commented on js/script.js
> +    function checkActiveMenu() {
Просто не работает, видимо, рано выполняешь

2024-12-04 22:17 UTC, bushkovsky commented on js/script.js
> +    };
Дело в том, что performance.now() в момент вызова timeToLoadJs измеряет время, прошедшее с момента загрузки страницы (точнее, с момента начала работы JavaScript), а не абсолютное время с начала загрузки страницы. Это может привести к расхождению в отображаемом времени загрузки страницы, так как функция может быть вызвана уже после некоторой задержки, например, при запуске скрипта или вызове timeToLoadJs.

2024-12-11 19:24 UTC, merged